spring.application.name=hexa-system
spring.datasource.url= ${URL_BD}
spring.datasource.username= ${USERNAME}
spring.datasource.password= ${PASSWORD}

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true

decoleta.token= ${TOKEN_DECO}
decoleta.base-url= https://api.decolecta.com/
key.signature= ${KEY_SIGNATURE}
stripe.secret-key=${TOKEN_STRIPE}